// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Transfer.Models
{
    public partial class money_transctionsContext : DbContext
    {
        public money_transctionsContext()
        {
        }

        public money_transctionsContext(DbContextOptions<money_transctionsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<transaction> transactions { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<transaction>(entity =>
            {
                entity.HasKey(e => e.idtransactions);

                entity.Property(e => e.borrower_name).HasMaxLength(50);
                entity.Property(e => e.lender_name).HasMaxLength(50);
                entity.Property(e => e.transaction_date).HasColumnType("date");
                entity.Property(e => e.transaction_type).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);



    }
}